version: '3'
services:
  app:
    build:
      context: ./
    volumes:
      - .:/var/www/html  
      - .env.prod:/var/www/html/.env    
    ports:
      - "8081:80"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
